version: '2'
services:
  screenshots:
    build:
      context: .
    ports:
      - "3000:3000"
    links:
      - selenium
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      SCREEN_WIDTH: 1080
      SCREEN_HEIGHT: 2280
      SCREEN_DEPTH: 24
