version: '2'
services:
  # screenshots:
  #   build:
  #     context: .
  #   ports:
  #     - "3000:3000"
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      SCREEN_WIDTH: 1080
      SCREEN_HEIGHT: 2280
      SCREEN_DEPTH: 24
